name: Run Python Script

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to Github runner.

      - name: Set up Python
        uses: actions/setup-python@v2 # This sets up Python in the runner.
        with:
          python-version: '3.x' 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the Script
        run: python main.py

